### ISSUE TITLE
NoMethodError: undefined method `encode' for Hash:Class

### ISSUE THREAD

**Issue by ryan-lingle** [bumi/lnrpc#2]
`lnd = Lnrpc::Client.new({credentials: cert, macaroon: macaroon})
lnd.get_info`

Continue to get: NoMethodError: undefined method `encode' for Hash:Class

**Comment by bumi** [comment]
Hi, thanks for reporting this! 
I've seen that before, but forgot what exactly the problem was. :(

Can you make sure that you are using the latest version of the gem? v0.5.2 - I've just now released a new version that depends on newer versions of grpc and google-protobuf gems with some bug fixes. 

what ruby version are you using?

**Comment by ryan-lingle** [comment]
Yes, I believe that was it! Thanks! I have another issue but I am pretty sure it entirely unrelated and something other people may run into so I will put it in another issue.
